In [ ]:
# import libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# read csv
df = pd.read_csv('Train_Dataset.csv')
test_df = pd.read_csv('Test_Dataset.csv')

<ipython-input-92-ddd9eecd5923>:2: DtypeWarning: Columns (1,7,8,16,17,18,19,20,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Train_Dataset.csv')
<ipython-input-92-ddd9eecd5923>:3: DtypeWarning: Columns (7,8,16,17,18,19,20,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  test_df = pd.read_csv('Test_Dataset.csv')

In [ ]:
# deal with na values if any
df.isna()

,ID,Client_Income,Car_Owned,Bike_Owned,Active_Loan,House_Own,Child_Count,Credit_Amount,Loan_Annuity,Accompany_Client,...,Client_Permanent_Match_Tag,Client_Contact_Work_Tag,Type_Organization,Score_Source_1,Score_Source_2,Score_Source_3,Social_Circle_Default,Phone_Change,Credit_Bureau,Default
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,True,True,True,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121851,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
121852,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
121853,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,True,False
121854,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
121855,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [ ]:
# replace na values
df.fillna(df.mean(), inplace=True)
test_df.fillna(test_df.mean(), inplace=True)
df = df.fillna(df.mode().iloc[0])
test_df = test_df.fillna(test_df.mode().iloc[0])

df.isna()

<ipython-input-94-b86a5742dedc>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean(), inplace=True)
<ipython-input-94-b86a5742dedc>:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  test_df.fillna(test_df.mean(), inplace=True)

,ID,Client_Income,Car_Owned,Bike_Owned,Active_Loan,House_Own,Child_Count,Credit_Amount,Loan_Annuity,Accompany_Client,...,Client_Permanent_Match_Tag,Client_Contact_Work_Tag,Type_Organization,Score_Source_1,Score_Source_2,Score_Source_3,Social_Circle_Default,Phone_Change,Credit_Bureau,Default
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121851,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
121852,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
121853,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
121854,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
121855,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Label Encoding
# 1. find columns with object
# 2. apply label encoder in loop
col = df.select_dtypes(include = 'object').columns
col

Index(['Client_Income', 'Credit_Amount', 'Loan_Annuity', 'Accompany_Client',
       'Client_Income_Type', 'Client_Education', 'Client_Marital_Status',
       'Client_Gender', 'Loan_Contract_Type', 'Client_Housing_Type',
       'Population_Region_Relative', 'Age_Days', 'Employed_Days',
       'Registration_Days', 'ID_Days', 'Client_Occupation',
       'Client_Permanent_Match_Tag', 'Client_Contact_Work_Tag',
       'Type_Organization', 'Score_Source_3'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in col:
    df[feat] = le.fit_transform(df[feat].astype(str))

In [ ]:
test_col=test_df.select_dtypes(include='object').columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in col:
    test_df[feat] = le.fit_transform(test_df[feat].astype(str))

In [ ]:
# Splitting in  training and testing data
x_train, y_train = df.drop('Default', axis=1), df['Default']
# x_test, y_test = test_df.drop('Default', axis=1), test_df['Default']

In [ ]:
# importing libraries for neural network
from keras import models
from keras import layers

In [ ]:
# creating neural network
network = models.Sequential()
# initial input size
network.add(layers.Dense(512, activation='relu'))
# subsequent hidden layer
network.add(layers.Dense(256, activation='relu'))
# subsequent hidden layer
network.add(layers.Dense(256, activation='relu'))
# final output (in our case 0-9 image)
network.add(layers.Dense(1, activation='sigmoid'))

In [ ]:
# gradient, loss function, metrics
network.compile(optimizer='rmsprop', # same as ngradient
loss = 'binary_crossentropy',   # loss function is cross entropy
metrics=['accuracy'])                # evaluation matrix is accuracy

In [ ]:
# Our vectorized labels
y_train = np.asarray(y_train).astype('float32').reshape((-1,1))

In [ ]:
# epochs is no of times it should run
network.fit(x_train, y_train, epochs=10, batch_size=64, validation_split=0.2)

Epoch 1/10
1524/1524 [==============================] - 13s 8ms/step - loss: 8525.2178 - accuracy: 0.8928 - val_loss: 0.2801 - val_accuracy: 0.9195
Epoch 2/10
1524/1524 [==============================] - 11s 7ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2802 - val_accuracy: 0.9195
Epoch 3/10
1524/1524 [==============================] - 12s 8ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2801 - val_accuracy: 0.9195
Epoch 4/10
1524/1524 [==============================] - 12s 8ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2802 - val_accuracy: 0.9195
Epoch 5/10
1524/1524 [==============================] - 12s 8ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2806 - val_accuracy: 0.9195
Epoch 6/10
1524/1524 [==============================] - 12s 8ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2810 - val_accuracy: 0.9195
Epoch 7/10
1524/1524 [==============================] - 11s 7ms/step - loss: 0.2810 - accuracy: 0.9191 - val_loss: 0.2805 - val_accuracy: 0.9195
Epoch 8/10
1524/1524 [==============================] - 10s 7ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2801 - val_accuracy: 0.9195
Epoch 9/10
1524/1524 [==============================] - 13s 8ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2801 - val_accuracy: 0.9195
Epoch 10/10
1524/1524 [==============================] - 11s 7ms/step - loss: 0.2811 - accuracy: 0.9191 - val_loss: 0.2802 - val_accuracy: 0.9195

In [ ]:
# summary
network.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 512)               20480

 dense_25 (Dense)            (None, 256)               131328

 dense_26 (Dense)            (None, 256)               65792

 dense_27 (Dense)            (None, 1)                 257

=================================================================
Total params: 217,857
Trainable params: 217,857
Non-trainable params: 0
_________________________________________________________________